Repository SOPT-TEAM9-Carrot/Carrot-SERVER, pull requests merged in 2023-05, with the labels that each got.

#2 [init] : 초기세팅
  carrotServer/gradle/wrapper/gradle-wrapper.jar
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/ErrorType.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/JsonResponse.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/SuccessType.java
Labels: 서린🐱, pull request🔥

#4 #3 [feat] post,category 엔티티생성
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/category/CategoryEntity.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/category/CategoryRepository.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/category/CategoryRepositoryImpl.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/post/PostEntity.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/post/PostRepository.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/post/PostRepositoryImpl.java
Labels: feat

#6 #1 [feat] User, Review 엔티티 구현
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/review/ReviewEntity.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/review/ReviewRepository.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/review/ReviewRepositoryImpl.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/user/UserEntity.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/user/UserRepository.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/user/UserRepositoryImpl.java
Labels: 영주🐼, feat, pull request🔥

#8 #5 [feat] post 핵심 로직 구현
  .github/.gitmessage.txt
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/post/Category.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/post/Post.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/category/CategoryEntity.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/post/PostEntity.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/post/PostRepository.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/post/PostService.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/post/PostServiceImpl.java
Labels: feat, 서린🐱, pull request🔥

#10 #7 [feat] User 핵심 로직 구현
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/user/User.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/user/UserEntity.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/user/UserRepository.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/user/UserRepositoryImpl.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/user/UserService.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/user/UserServiceImpl.java
Labels: 영주🐼, feat, pull request🔥

#12 #11 [feat] employer 핵심 로직 구현
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/employer/Review.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/employer/User.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/review/ReviewEntity.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/review/ReviewRepository.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/review/ReviewRepositoryImpl.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/infrastructure/user/UserEntity.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/employer/EmployerService.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/employer/EmployerServiceImpl.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/user/UserService.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/user/UserServiceImpl.java
Labels: 영주🐼, feat, pull request🔥

#14 #9 [feat] Post Controller 추가
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/SuccessType.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/post/PostController.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/post/dto/response/PostListResponse.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/post/dto/response/PostResponse.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/post/dto/response/RecommendPostListResponse.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/post/dto/response/RecommendPostResponse.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/employer/User.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/post/Category.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/post/Post.java
Labels: feat, 서린🐱, pull request🔥

#17 #16 [feat] : Post User Profile api 완성
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/SuccessType.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/user/UserController.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/user/dto/request/CreateUserProfileRequest.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/user/dto/response/CreateUserProfileResponse.java
Labels: feat, 서린🐱

#15 #13 [feat] Employer Controller 구현
  carrotServer/src/main/java/cds/carrot/org/carrotServer/CarrotServerApplication.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/ControllerExceptionAdvice.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/ErrorType.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/JsonResponse.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/SuccessType.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/EmployerController.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/dto/response/EmployerResponseDto.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/post/PostController.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/employer/Review.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/employer/User.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/exception/ApiException.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/exception/BadRequestException.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/exception/NotFoundException.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/employer/EmployerService.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/employer/EmployerServiceImpl.java
Labels: 영주🐼, feat, pull request🔥

#18 [docs] : README 업데이트
  README.md
Labels: 서린🐱, docs, pull request🔥

#21 #20 [fix] 예외처리 구현 및 코딩컨벤션 검토
  carrotServer/src/main/java/cds/carrot/org/carrotServer/CarrotServerApplication.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/ControllerExceptionAdvice.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/CustomInterceptor.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/WebMvcConfig.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/ErrorType.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/JsonResponse.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/common/dto/SuccessType.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/EmployerController.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/employer/dto/response/EmployerResponse.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/post/PostController.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/post/dto/response/RecommendPostResponse.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/user/UserController.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/controller/user/dto/request/CreateUserProfileRequest.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/domain/post/Post.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/exception/BadRequestException.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/exception/NotFoundException.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/employer/EmployerService.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/employer/EmployerServiceImpl.java
  carrotServer/src/main/java/cds/carrot/org/carrotServer/service/post/PostServiceImpl.java
Labels: fix, 영주🐼, pull request🔥
